### ISSUE TITLE
Arrange basics artwork

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#12]
Arrange basics artwork stored in `design/artwork` subfolders and intended to decorate the basic structure, such as:

- [x] `/backgrounds`
  - [x] `README.md`
  - [x] `/generic`: this folder aims to contain background pictures (named `background-*.jpg`) used in `body-background.php` set in #8
- [x] `/brands`
  - [x] `README.md`
  - [x] `/portable`: this folder aims to contain `png` files (named `favicon-*.png`) used in `icon-data.php` set in #4
  - [x] `/scalable`: this folder contains `svg` files, such as:
    - [x] `mergey.svg`: the main emblem of the site, specifically adjusted to fit the project (to be display in `header.php` set in #6)
    - [x] five brand `svg` icons directly pulled from the [Simple Icons](https://github.com/simple-icons/simple-icons) project (to be used with data from `networks.json` set in #14)
