### ISSUE TITLE
Compose proof layout

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#15]
Compose the `proof.php` file positioned at the root of the site in order to display legal or statutory informations, split into distinct inclusions (stored in `/layout/reusable` folder).

- `/`
  - [x] `proof.php`
- `/layout/parceled`
  - [x] `proof-contact.php`, for displaying (with embedding of texts from #16)
    - [x] `<address>` element from `div-itemprop-contactpoint.php` set in #8
    - [x] `<ul>` element gathering networks links for `ul-networks.php` set in #8
  - [x] `proof-imprint.php`, for displaying:
    - [x] `<address>` element composed by 
      - [x] `div-itemprop-name.php` set in #8
      - [x] `div-itemprop-address.php` set in #8
      - [x] `div-itemprop-contactpoint.php` set in #8
