### ISSUE TITLE
Prepare transcribed texts

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#16]
Prepare various texts to be included in different files. 

## common items

A gathering of these texts must be usable according to the selected language (stored in the `/en` or` /fr` subfolders of the `/speech` folder):

- Files intended to be integrated into final version
  - [x] `alert-language.md`: used in`div-alert-language.php` set in #8
  - [x] `contact-email.md`: used in `proof-contact.php` set in #15
  - [x] `contact-networks.md`: used in `proof-contact.php` set in #15
  - [x] `error-302.md`: used in `error.php` set in #19
  - [x] `error-404.md`: used in `error.php` set in #19
  - [x] `index-axiom.md`: used in `index.php` set in #20
  - [x] `index-motto.md`: used in `index.php` set in #20
- Files intended to be integrated temporary during provisional version
  - [x] `index-patch.md`: used in `index.php` set in #20

## particular items

Another group are intended to be only used with the core business language (therefore only stored in the subfolder `/fr` in the `/speech` folder):

- [x] `stall-activities.md`: displayed by `stall.php` set in #18
- [x] `stall-principles.md`: displayed by `stall.php` set in #18

**Comment by gizmecano** [comment]
Due to #32, this task for inputting and translating may be considered **retroactively** as having been fully completed during the preceding `beta.2` phase (and additional adjustment works can be considered separately in further issues, such as case of #41).
