### ISSUE TITLE
Configure server settings

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#17]
Configure various initial server settings, such as:

- [x] `.htaccess`
  - [x] `mod_expires`
  - [x] `mod_deflate`
  - [x] `mod_rewrite`
    - [x] `RewriteRule` for version 1
    - [x] `RewriteRule` for version 3
    - [x] `RewriteRule` rules for for basic home page
      - [x] `index.php` set in #20
    - [x] `RewriteRule` rules for root positioned pages
      - [x] `error.php` set in #19
      - [x] `proof.php` set in #15
      - [x] `stall.php` set in #18
  - [x] `ErrorDocument` rules for specified error pages set in #19
- [x] `.ovhconfig`
- [x] `robots.txt`
