### ISSUE TITLE
Prepare basics layout

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#2]
Prepare basics layout, using the canvas of main `index.php` page in order to set and position main structural elements.

The initial `index.php` file will be able to be used to build a generic template `model.php` for other page layouts.

Items indicated using bold font below are considered as inner elements for the basics layout:

- [x] `index.php`
  - [x] `<html>`: `lang` attribute defined in #4
  - [x] `<head>`: detailed content in #3 
  - [x] **`<body>`**: with an unique `id` (in order to distinct type of page)
  - [x] **`<div class="flex-container">`**: a global container (based on [flexbox layout](https://www.alsacreations.com/tuto/lire/1493-css3-flexbox-layout-module.html))
  - [x] `<header>`: detailed content in #6
  - [x] **`<main>`**: element for positioning the main content of the page
  - [x] `<footer>`: detailed content in #7 
  - [x] `<div id="full-page-background">`: detailed content in #8
- [x] `model.php`
