### ISSUE TITLE
Prepare short-term index layout

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#20]
Prepare index layout with some specificities (distinct from `model.php`) and in order to display short-term content (beta version only).

- [x] `index.php`
  - [x] `<header>`
    - [x] `<h2>` using a `visually-hidden` class
    - [x] `<p>` (displaying `index-motto.md` set in #16)
    - [x] `<div>` containing `<img>` (displaying **temporarily** the default image defined in #4)
    - [x] `<p>` (displaying `index-axiom.md` set in #16)
  - [x] `<section>`
    - [x] `<p>` (displaying **temporarily** `index-patch.md` set in #16)
