### ISSUE TITLE
Prepare head element

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#3]
Prepare the `<head>` element by listing all the components that must be embedded in a `head.php` file set in `/layout` folder.

- [x] `<base>`
- [x] `<meta>`: three initial meta for `charset`, `http-equiv` and `name="viewport"`
- [x] `<title>`: composed in `page-data.php` set in #4 
- [x] `<link rel="canonical">`: composed in `page-data.php` set in #4 
- [x] `<link rel="stylesheet">`: links to implemented independent components set in #5
- [x] various shortcut icons, including formats such `rel="apple-touch-icon-precomposed"`, `rel="shortcut icon"` and `rel="icon"`, set in `icon-data.php` set in #4.
