### ISSUE TITLE
Prepare required inclusions

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#4]
Prepare inclusions (stored in the `/required` subfolder set in the `/layout` folder) which can be required be several type of pages, mainly for defining significant variables.

- [x] `icon-data.php`: arrange and combine various size values for displaying selected shortcut icons (set in #12) including formats such as:
  - [x] `rel="apple-touch-icon-precomposed"`
  - [x] `rel="shortcut icon"`
  - [x] `rel="icon"`
- [x] `meta-data.php`: organized values ​​for online sharing tools
    - [x] [Schema properties](https://schema.org/)
    - [x] [OpenGraph properties](https://www.ogp.me/)
    - [x] [Twitter names](https://developer.twitter.com/en/docs/tweets/optimize-with-cards/overview/markup)
- [x] `site-data.php`: global values ​​for whole site, such as:
   - [x] `host` : full string of the host (including local and remote variants with `http` or `https` protocols)
   - [x] `lang` : default language collected from server variables
   - [x] `name` : general site name (pulled from composer data set in #10)
   - [x] `mail`: value composed (using value from composer data set in #10)
- [x] `page-data.php`: specific page values, such as:
   - [x] `lang` : language to use in the page, depending on a specifically defined value or the default language
   - [x] some metadata have to be composed according to page type
      - [x] `blurb`: blurb for describing the page content
      - [x] `canon`: canonical link of the page
      - [x] `image`: image depicting the page content
      - [x] `title`: title of the page
