### ISSUE TITLE
Prepare footer element

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#7]
Prepare the main `<footer>` element in a `footer.php` file set in `/layout` folder. This file is intended to only contain a loop organizing four separate proportional sections stored in the `/parceled` sub-folder.

1. `/`
   - [x] `footer.php`: containing a loop organizing the sections listed below
2. `/parceled`
   - [x] `footer-part-1.php`: for displaying an `<ul>` element gathering content from `stall.php` layout set in #18
   - [x] `footer-part-2.php` for displaying an `<ul>` element devoted to other personal projects (set inline)
   - [x] `footer-part-3.php`: for displaying an `<ul>` element gathering networks links from `ul-networks.php` set in #8
   - [x] `footer-part-4.php`: which would display:
      - [x] `<address>`: element containing contact point informations from:
        - [x] `div-itemprop-name.php` set in #8
        - [x] `div-itemprop-address.php` set in #8
      - [x] `<ul>`: element gathering statutory informations (set in #15)
      - [x] `<ul>`: element gathering accessory informations
