### ISSUE TITLE
Overhaul existing milestones for clarifying roadmap

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#72]
Due to the too sparing progress made during lately, it could be useful to clean up tasks which were started and/or planned, in order to clarify a conceivable roadmap.

Consequently, this issue concerns an overhaul, as exhaustive as possible, of the previously `beta` [envisaged milestones](https://github.com/gizmecano/mergey.ch/milestones).

- [ ] Review tasks set in `4.0.0-beta.3` milestone
- [ ] Review tasks set in `4.0.0-beta.4` milestone
- [ ] Review tasks set in `4.0.0-beta.5` milestone
