### ISSUE TITLE
Prepare reusable inclusions

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#8]
Prepare inclusions (stored in the `/reusable` subfolder set in the `/layout` folder) which can be embedded in several type of pages, mainly for organizing content intended to be used more than once.

- [x] `body-background.php`: visual block intended to display a full page background picture (set in #12) depending on the type of page
- [x] `div-alert-language.php`: a `<div role="alert">` element for displaying a warning (set in #16) if the language content doesn't match the supposed visitor language
- [x] `ul-networks.php`: list of links to various social networks (generated from the `networks.json` file set in #14) used for `footer-part-4.php` set in #7 

Elements representing various item properties and structured according to the [Schema.org](https://schema.org/) vocabulary, which can be combined and adjusted as required:
- [x] `div-itemprop-address.php`: required for `footer-part-4.php` set in #7 and `proof-imprint.php` set in #15
- [x] `div-itemprop-contactpoint.php`: required for `proof-imprint.php` and `proof-contact.php` set in #15
- [x] `div-itemprop-name.php`: required for `footer-part-4.php` set in #7 and `proof-imprint.php` set in #15
