### ISSUE TITLE
Design custom stylesheet for basics elements

### ISSUE THREAD

**Issue by gizmecano** [gizmecano/mergey-4-scrapped#9]
Design custom stylesheet file `bedrock.css` set in `/design/styling` folder in order to specify styles for all basics elements, _ie_. the main bedrock of the whole site, but also various structural elements such as:

- [x] `/index.php` file set in #2
- [x] `/layout/footer.php` file set in #7
- [x] `/layout/header.php` file set in #6
- [x] `/layout/reusable` files in #8
